apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:4.0.17
        name: mongodb
        ports: 
        - containerPort: 27017
        volumeMounts:
        - name: mongodb
          mountPath: /data/db 
      volumes:
      - name: mongodb
        hostPath: 
          path: /tmp/mongoDB
          type: DirectoryOrCreate
